// <auto-generated />
using System;
using BidZone.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BidZone.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BidZone.Domains.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ReservePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ConcurrencyStamp = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            CurrentPrice = 999.99m,
                            Description = "Brand new iPhone 15 Pro Max 256GB",
                            EndTime = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/iphone15/860/600",
                            SellerId = 2,
                            Slug = "",
                            StartTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 999.99m,
                            Status = "Active",
                            Title = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            ConcurrencyStamp = new Guid("a1b2c3d4-0002-0000-0000-000000000002"),
                            CurrentPrice = 15000m,
                            Description = "1960s Rolex Submariner in excellent condition",
                            EndTime = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/rolex/860/600",
                            SellerId = 2,
                            Slug = "",
                            StartTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 15000m,
                            Status = "Active",
                            Title = "Vintage Rolex Submariner"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ConcurrencyStamp = new Guid("a1b2c3d4-0003-0000-0000-000000000003"),
                            CurrentPrice = 800m,
                            Description = "Trek X-Caliber 8, barely used",
                            EndTime = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/trek/860/600",
                            SellerId = 2,
                            Slug = "",
                            StartTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 800m,
                            Status = "Active",
                            Title = "Mountain Bike Trek"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ConcurrencyStamp = new Guid("a1b2c3d4-0004-0000-0000-000000000004"),
                            CurrentPrice = 250m,
                            Description = "Original oil painting, 24x36 inches",
                            EndTime = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/painting/860/600",
                            SellerId = 2,
                            Slug = "",
                            StartTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 250m,
                            Status = "Active",
                            Title = "Oil Painting - Sunset"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 8,
                            ConcurrencyStamp = new Guid("a1b2c3d4-0005-0000-0000-000000000005"),
                            CurrentPrice = 35000m,
                            Description = "Tesla Model 3 Long Range, white, 10k miles",
                            EndTime = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://picsum.photos/seed/tesla/860/600",
                            SellerId = 2,
                            Slug = "",
                            StartTime = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 35000m,
                            Status = "Active",
                            Title = "Tesla Model 3 2023"
                        });
                });

            modelBuilder.Entity("BidZone.Domains.Entities.AuctionImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("AuctionImages");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int>("BidderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.BrowsingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SearchTerm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("BrowsingEvents");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Art",
                            Slug = "art"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Interiors",
                            Slug = "interiors"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jewellery",
                            Slug = "jewellery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Watches",
                            Slug = "watches"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fashion",
                            Slug = "fashion"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Coins & Stamps",
                            Slug = "coins-stamps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Comics",
                            Slug = "comics"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cars & Bikes",
                            Slug = "cars-bikes"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Wine & Spirits",
                            Slug = "wine-spirits"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Collectibles",
                            Slug = "collectibles"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sports",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Books",
                            Slug = "books"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Toys",
                            Slug = "toys"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Photography",
                            Slug = "photography"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Musical",
                            Slug = "musical"
                        });
                });

            modelBuilder.Entity("BidZone.Domains.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BidZone.Domains.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a6560ca-cd10-4f76-b0e7-bf8ce5caa5db",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bidzone.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BIDZONE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZHtCrpw/j1RV8ISXtKMS02S7jhq1dOzqyCRABr07G8TUzI4aIMYWuS7gRMeHSPnQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "d44e0d8f-0f86-4a4e-a1d9-a6bf29f50a41",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ec1d3f44-1730-4bd3-836d-a7da7318afdb",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seller1@bidzone.com",
                            EmailConfirmed = true,
                            FullName = "Demo Seller",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SELLER1@BIDZONE.COM",
                            NormalizedUserName = "SELLER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOKn3iS6zRXJxbYnH6fG8R8bds/7coXisLNnePfdl5rCa0DW6Ot8z1NGUFbv4oCzUg==",
                            PhoneNumberConfirmed = false,
                            Role = "Seller",
                            SecurityStamp = "d15f4865-12ec-4880-9a8e-efec8d61cb08",
                            TwoFactorEnabled = false,
                            UserName = "seller1"
                        },
                        new
                        {
                            Id = 1000,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f0e1d2c3-b4a5-6789-0123-456789abcdef",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bidzone@admin.com",
                            EmailConfirmed = true,
                            FullName = "BidZone Admin",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BIDZONE@ADMIN.COM",
                            NormalizedUserName = "BIDZONE",
                            PasswordHash = "AQAAAAIAAYagAAAAEKyY8Y+6VNQGOb6NT850FBSBAjw+eJjswfXEelYY8zvEfyP3O4vpyk21PMSKa1tOFQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "b1d2a3c4-5e6f-7890-abcd-ef0123456789",
                            TwoFactorEnabled = false,
                            UserName = "bidzone"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "87fda966-f7ca-4f43-a6f2-dcb92c1a24cf",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buyer1@bidzone.com",
                            EmailConfirmed = true,
                            FullName = "Demo Buyer",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BUYER1@BIDZONE.COM",
                            NormalizedUserName = "BUYER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEOxt2/uhhLlq+OgQNwz+4tkYkTas/HpQkGc/LtTIqctryoEiRDsrvJEqQ6AChKzgCQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Buyer",
                            SecurityStamp = "9db95bff-3eeb-4a2d-afd1-af80e0c31db2",
                            TwoFactorEnabled = false,
                            UserName = "buyer1"
                        });
                });

            modelBuilder.Entity("BidZone.Domains.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId", "AuctionId")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BidZone.Domains.Entities.Auction", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidZone.Domains.Entities.User", "Seller")
                        .WithMany("Auctions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.AuctionImage", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.Auction", "Auction")
                        .WithMany("Images")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.Bid", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidZone.Domains.Entities.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.BrowsingEvent", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.Auction", "Auction")
                        .WithMany("BrowsingEvents")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BidZone.Domains.Entities.Category", "Category")
                        .WithMany("BrowsingEvents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BidZone.Domains.Entities.User", "User")
                        .WithMany("BrowsingEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.RefreshToken", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.WatchlistItem", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.Auction", "Auction")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidZone.Domains.Entities.User", "User")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BidZone.Domains.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BidZone.Domains.Entities.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("BrowsingEvents");

                    b.Navigation("Images");

                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.Category", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("BrowsingEvents");
                });

            modelBuilder.Entity("BidZone.Domains.Entities.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");

                    b.Navigation("BrowsingEvents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
