// <auto-generated />
using System;
using BidZone.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BidZone.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320124421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BidZone.Models.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ReservePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CurrentPrice = 999.99m,
                            Description = "Brand new iPhone 15 Pro Max 256GB",
                            EndTime = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/iphone15.jpg",
                            SellerId = 2,
                            StartTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 999.99m,
                            Status = "Active",
                            Title = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 8,
                            CurrentPrice = 15000m,
                            Description = "1960s Rolex Submariner in excellent condition",
                            EndTime = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/rolex.jpg",
                            SellerId = 2,
                            StartTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 15000m,
                            Status = "Active",
                            Title = "Vintage Rolex Submariner"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CurrentPrice = 800m,
                            Description = "Trek X-Caliber 8, barely used",
                            EndTime = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/trek.jpg",
                            SellerId = 2,
                            StartTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 800m,
                            Status = "Active",
                            Title = "Mountain Bike Trek"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            CurrentPrice = 250m,
                            Description = "Original oil painting, 24x36 inches",
                            EndTime = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/painting.jpg",
                            SellerId = 2,
                            StartTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 250m,
                            Status = "Active",
                            Title = "Oil Painting - Sunset"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CurrentPrice = 35000m,
                            Description = "Tesla Model 3 Long Range, white, 10k miles",
                            EndTime = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "/images/tesla.jpg",
                            SellerId = 2,
                            StartTime = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 35000m,
                            Status = "Active",
                            Title = "Tesla Model 3 2023"
                        });
                });

            modelBuilder.Entity("BidZone.Models.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int>("BidderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("BidderId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("BidZone.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vehicles",
                            Slug = "vehicles"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion",
                            Slug = "fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden",
                            Slug = "home-garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports",
                            Slug = "sports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Art & Collectibles",
                            Slug = "art-collectibles"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Books & Media",
                            Slug = "books-media"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Jewelry & Watches",
                            Slug = "jewelry-watches"
                        });
                });

            modelBuilder.Entity("BidZone.Models.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BidZone.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bidzone.com",
                            IsActive = true,
                            PasswordHash = "0192023a7bbd73250516f069df18b500",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "seller1@bidzone.com",
                            IsActive = true,
                            PasswordHash = "e10adc3949ba59abbe56e057f20f883e",
                            Role = "Seller",
                            Username = "seller1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "buyer1@bidzone.com",
                            IsActive = true,
                            PasswordHash = "e10adc3949ba59abbe56e057f20f883e",
                            Role = "Buyer",
                            Username = "buyer1"
                        });
                });

            modelBuilder.Entity("BidZone.Models.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuctionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId", "AuctionId")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("BidZone.Models.Entities.Auction", b =>
                {
                    b.HasOne("BidZone.Models.Entities.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidZone.Models.Entities.User", "Seller")
                        .WithMany("Auctions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BidZone.Models.Entities.Bid", b =>
                {
                    b.HasOne("BidZone.Models.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidZone.Models.Entities.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("BidZone.Models.Entities.Session", b =>
                {
                    b.HasOne("BidZone.Models.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidZone.Models.Entities.WatchlistItem", b =>
                {
                    b.HasOne("BidZone.Models.Entities.Auction", "Auction")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidZone.Models.Entities.User", "User")
                        .WithMany("WatchlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidZone.Models.Entities.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("WatchlistItems");
                });

            modelBuilder.Entity("BidZone.Models.Entities.Category", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("BidZone.Models.Entities.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");

                    b.Navigation("Sessions");

                    b.Navigation("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
